import type { App } from 'vue';
export default function DataV(app: App, { classNamePrefix }?: {
    classNamePrefix?: string;
}): void;
export { setClassNamePrefix } from './utils/styled';
export * from './components/border-box-1';
export * from './components/border-box-2';
export * from './components/border-box-3';
export * from './components/border-box-4';
export * from './components/border-box-5';
export * from './components/border-box-6';
export * from './components/border-box-7';
export * from './components/border-box-8';
export * from './components/border-box-9';
export * from './components/border-box-10';
export * from './components/border-box-11';
export * from './components/border-box-12';
export * from './components/border-box-13';
export * from './components/decoration-1';
export * from './components/decoration-2';
export * from './components/decoration-3';
export * from './components/decoration-4';
export * from './components/decoration-5';
export * from './components/decoration-6';
export * from './components/decoration-7';
export * from './components/decoration-8';
export * from './components/decoration-9';
export * from './components/decoration-10';
export * from './components/decoration-11';
export * from './components/decoration-12';
export * from './components/loading';
export type { RefreshLayoutSize, ExposeWithRefreshLayoutSize } from './hooks/useResize';
